package com.leetcode.findthedifference;

/**
 * Given two strings s and t which consist of only lowercase letters.
 *
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 *
 * Find the letter that was added in t.
 *
 * Example:
 *
 * Input:
 * s = "abcd"
 * t = "abcde"
 *
 * Output:
 * e
 *
 * Explanation:
 * 'e' is the letter that was added.
 */
public class FindTheDifference {
    public static char findTheDifference(String s, String t) {
        long sourceSum = 0;
        long destSum = 0;
        for (char ch : s.toCharArray()) {
            sourceSum += ch;
        }
        for (char ch : t.toCharArray()) {
            destSum += ch;
        }

        return (char) (destSum - sourceSum);
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("a", "aa"));
    }
}
